### ISSUE TITLE
请问原作者在utils中写的代码有什么作用？

### ISSUE THREAD

**Issue by jxhsccd** [userbehavioranalysis/SR-GNN-Chinese_Comment_edition#2]
开始以为是用utils来构图，后面发现main里完全没有引用到utils中的代码？

**Comment by Dongzhixiao** [comment]
utils这段代码是一个数据处理的类Data，提供了数据的预处理和生成批数据的方法。包括：

1. build_graph函数：构建图
2. data_masks函数：将所有输入序列按照最长长度尾部补全
3. split_validation函数：将训练集按照比例分为训练集和验证集
4. Data类的generate_batch方法：根据批的大小生成批数据的索引，如果shuffle则打乱数据
5. Data类的get_slice方法：根据索引i得到对应的数据
